### ISSUE TITLE
Unknown Vagrant box

### ISSUE THREAD

**Issue by lavoiesl** [opskeleton/artifactory-sandbox#2]
The Vagrantfile references an unknown box:

```
artifactory.vm.box = 'ubuntu-14.10_puppet-3.7.3' 
```

Perhaps consider using https://vagrantcloud.com/puppetlabs/boxes/ubuntu-14.04-64-puppet ?

**Comment by narkisr** [comment]
My main issue with the puppet labs boxes is the lack of versioning the puppet installed within them

Also from experience they move slower in updating them regularly, right now the opsk [recommended](https://github.com/opskeleton/opskeleton#boxes) way is to use packer and boxcuter  and build them locally.

Ill probably create a droplet hosting the boxes I use, when that will be available ill start setting the urls in the Vagrant file.

Thanks

**Comment by lavoiesl** [comment]
And I changed it in my local Vagrantfile and it worked without a glitch. You can always to apt-get update / upgrade / whatever or pin a version if you so desire.

Having a custom brewed box is nice for super reliable and enterprise-grade solution, but Vagrant boxes is also meant for spinning up a software to try it out.

**Comment by narkisr** [comment]
I'm glad that it worked just fine, still id rather control the box production and not depend on third parties (as you found out its pretty easy to use other boxes)

Thanks
